### ISSUE TITLE
Not working under Fedora 17

### ISSUE THREAD

**Issue by packplusplus** [pjr/keycode-idrac#1]
I used this hack successfully under F16, doesn't seem to work under F17.

When I follow /tmp/keycode-log:

Up: 111 
Down: 116
Left: 113 
Right:114

However it never announces it's mangling the key codes. Since code references keysymdef.h, I'm not sure why it's not recognized as XK_Up. Any hints on fixing this?

**Comment by pjr** [comment]
can you grab the keycodes from xev? You should see something like this (this is from X11 port in OSX). For each time you press a key, there's a KeyPress and a KeyRelease event. The important parts here are the keycode/keysym on the third line.

```
KeyPress event, serial 29, synthetic NO, window 0x600001,
    root 0x281, subw 0x0, time 2412013519, (15,-9), root:(15,13),
    state 0x0, keycode 131 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by packplusplus** [comment]
Here's what xdev outputs, which jives with the output coming out of the debug log. (this is up/down/left/right). 

KeyRelease event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170905950, (340,697), root:(365,898),
    state 0x0, keycode 111 (keysym 0xff52, Up), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170907702, (340,697), root:(365,898),
    state 0x0, keycode 116 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170907806, (340,697), root:(365,898),
    state 0x0, keycode 116 (keysym 0xff54, Down), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170908414, (340,697), root:(365,898),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170908502, (340,697), root:(365,898),
    state 0x0, keycode 113 (keysym 0xff51, Left), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170908950, (340,697), root:(365,898),
    state 0x0, keycode 114 (keysym 0xff53, Right), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyRelease event, serial 32, synthetic NO, window 0x2000001,
    root 0x385, subw 0x0, time 170909038, (340,697), root:(365,898),
    state 0x0, keycode 114 (keysym 0xff53, Right), same_screen YES,
    XLookupString gives 0 bytes:
    XFilterEvent returns: False

**Comment by packplusplus** [comment]
Closing, I lost context of if this is still an issue and don't want to clutter up the issues history.
